parameters:
    actualys_drupal_commerce_connector.processor.product.class: Actualys\Bundle\DrupalCommerceConnectorBundle\Processor\ProductProcessor
    actualys_drupal_commerce_connector.processor.family.class: Actualys\Bundle\DrupalCommerceConnectorBundle\Processor\FamilyProcessor
    actualys_drupal_commerce_connector.processor.attribute.class: Actualys\Bundle\DrupalCommerceConnectorBundle\Processor\AttributeProcessor
    actualys_drupal_commerce_connector.processor.attribute_option.class: Actualys\Bundle\DrupalCommerceConnectorBundle\Processor\AttributeOptionProcessor
    actualys_drupal_commerce_connector.processor.category.class: Actualys\Bundle\DrupalCommerceConnectorBundle\Processor\CategoryProcessor
    actualys_drupal_commerce_connector.processor.group.class: Actualys\Bundle\DrupalCommerceConnectorBundle\Processor\GroupProcessor
    actualys_drupal_commerce_connector.processor.association.class: Actualys\Bundle\DrupalCommerceConnectorBundle\Processor\AssociationProcessor

services:
    actualys_drupal_commerce_connector.processor.product:
        class: %actualys_drupal_commerce_connector.processor.product.class%
        arguments:
            - '@pim_catalog.manager.product'
            - '@pim_catalog.manager.channel'
            - '@actualys_drupal_commerce_connector.normalizer.product'
            
     actualys_drupal_commerce_connector.processor.productDeleted:
        class: %actualys_drupal_commerce_connector.processor.product.class%
        arguments:
            - '@pim_catalog.manager.product'
            - '@pim_catalog.manager.channel'
            - '@actualys_drupal_commerce_connector.normalizer.product'
            - %status.delete%

    actualys_drupal_commerce_connector.processor.family:
        class: %actualys_drupal_commerce_connector.processor.family.class%
        arguments:
            - '@actualys_drupal_commerce_connector.normalizer.family'

    actualys_drupal_commerce_connector.processor.attribute:
        class: %actualys_drupal_commerce_connector.processor.attribute.class%
        arguments:
            - '@actualys_drupal_commerce_connector.normalizer.attribute'

    actualys_drupal_commerce_connector.processor.attribute_option:
        class: %actualys_drupal_commerce_connector.processor.attribute_option.class%
        arguments:
            - '@actualys_drupal_commerce_connector.normalizer.attribute_option'

    actualys_drupal_commerce_connector.processor.category:
        class: %actualys_drupal_commerce_connector.processor.category.class%
        arguments:
            - '@actualys_drupal_commerce_connector.normalizer.category'

    actualys_drupal_commerce_connector.processor.group:
        class: %actualys_drupal_commerce_connector.processor.group.class%
        arguments:
            - '@actualys_drupal_commerce_connector.normalizer.group'

    actualys_drupal_commerce_connector.processor.association:
        class: %actualys_drupal_commerce_connector.processor.association.class%
        arguments:
            - '@actualys_drupal_commerce_connector.normalizer.association'
            -  '@pim_catalog.manager.product'
            -  '@pim_catalog.manager.association'
